"""Constants for the Yamaha component."""
DOMAIN = "ha_bark"
DATA_BARK = "bark_data"
ATTR_COPY = "copy"
ATTR_SOUND = "sound"
ATTR_ICON = "icon"
ATTR_GROUP = "group"
ATTR_URL = "url"
ATTR_BADGE = "badge"
ATTR_AUTO_COPY = "autocopy"